spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:

          '[/**]':
            allowed-origins: "http://localhost:4200"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
